In [2]:
import torch
import numpy as np
from torch.autograd import Variable #Parameters in the neuron network

In [5]:
np_data = np.arange(6).reshape((2,3))
torch_data = torch.from_numpy(np_data)
tensor2array = torch_data.numpy()

print(
    '\nnumpy\n', np_data,
    '\ntorch\n', torch_data,
    '\ntensor2array\n', tensor2array,
)


numpy
 [[0 1 2]
 [3 4 5]] 
torch
 
 0  1  2
 3  4  5
[torch.LongTensor of size 2x3]
 
tensor2array
 [[0 1 2]
 [3 4 5]]


In [6]:
# data = [[1, 2], [3, 4]]
data = [3, 4]
# data = np.array(data)
tensor = torch.FloatTensor(data)

print(
#     '\nnumpy:\n', np.matmul(data, data),
#     '\nnumpy:\n', data.dot(data),
#     '\ntorch:\n', torch.mm(tensor, tensor),
    '\ntorch:\n', tensor,
    '\ntorch:\n', torch.dot(tensor, tensor),
    '\ntorch:\n', tensor.dot(tensor)
)


torch:
 
 3
 4
[torch.FloatTensor of size 2]
 
torch:
 0.0 
torch:
 0.0


In [7]:
tensor = torch.FloatTensor([[1, 2], [3, 4]])
variable = Variable(tensor, requires_grad=True)

In [8]:
a = np.arange(4).reshape((2,2))
b = np.arange(4).reshape((2,2))
c = a.dot(b)
print(c)
print(b==3)
print(np.argmax(c, axis=1))

[[ 2  3]
 [ 6 11]]
[[False False]
 [False  True]]
[1 1]


In [34]:
A = np.arange(1,16).reshape((3,5))
print(A)
print(A.T)
print(np.max(A))
print(np.median(A))
print(np.cumsum(A))
print(np.diff(A))
print(np.nonzero(A))
print(A.clip(5, 9))
print(A)
np.arange

B = np.arange(14, 2, -1)
print(B)
print(B.T)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
15
8.0
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]), array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))
[[5 5 5 5 5]
 [6 7 8 9 9]
 [9 9 9 9 9]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[14 13 12 11 10  9  8  7  6  5  4  3]
[14 13 12 11 10  9  8  7  6  5  4  3]


In [43]:
for row in A:
    print(row)
for column in A.T:
    print(column)
for item in A.flat:
    print(item)
    
A.flatten()

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
[ 1  6 11]
[ 2  7 12]
[ 3  8 13]
[ 4  9 14]
[ 5 10 15]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
# Array Merge
A = np.array([1, 1, 1])[:, np.newaxis]
B = np.array([2, 2, 2])[:, np.newaxis]
C = np.vstack((A, B))
D = np.hstack((A, B))

print(C)
print(D)
print(A.shape, C.shape)
print(D.shape)
print(A[np.newaxis, :].shape)
print(A[:, np.newaxis])

E = np.concatenate((A, B, B, A), axis = 1)
print(E)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]
[[1 2]
 [1 2]
 [1 2]]
(3, 1) (6, 1)
(3, 2)
(1, 3, 1)
[[[1]]

 [[1]]

 [[1]]]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]
